name: Benchmark FMD Bandwith
on:

  schedule:
  - cron: "0 0,6,9,12,15,18,21 * * *"
  
jobs:
  benchmark:
    name: Test bandwidth
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@v2.0.0
        with:    
          timezone: America/Yellowknife
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Update Packages
        run: sudo apt-get -qq update -y
      # - name: Upgrade Packages
      #   run: sudo apt-get -qq upgrade -y        
      - name: Install iPerf3 & NodeJS
        run: sudo apt-get -qq install iperf3 nodejs -y
      - name: Test bandwith
        run: iperf3 -c sparcsonline.com -p 8881 -J --logfile "bandwidth.json"
      - name: Install Node Deps
        run: npm install
      - name: Run NodeJS
        run: node index.js
      - name: Delete bandwidth file
        run: rm bandwidth.json
      - name: commit changes and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update Readme with test results'
          push: true
          branch: main
          
  
