name: Benchmark FMD Bandwith
on:
  workflow_dispatch:

jobs:
  benchmark:
    name: Test bandwidth
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Update Packages
        run: sudo apt-get update -y
      - name: Install iPerf3
        run: sudo apt-get install iperf3 -y
      - name: get server IP
        run: IP=$(dig +short intellifirenwt.com); echo $IP
      - name: Test bandwith
        run: iperf3 -c $IP
      
      
        
  
