name: Benchmark FMD Bandwith
on:
  push:
   branches:
    - main    
  workflow_dispatch:

jobs:
  benchmark:
    name: Test bandwidth
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Update Packages
        run: sudo apt-get -qq update -y
      - name: Install iPerf3
        run: sudo apt-get -qq install iperf3 -y
      - name: Test bandwith
#        run: IP=$(dig +short intellifirenwt.com); echo $IP ; iperf3 -c $IP
#        run: iperf3 -c $(dig +short intellifirenwt.com)
        run: iperf3 -c sparcsonline.com -p 8881
      
      
        
  
